name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.tpl"
      - "**/*.py"
      - "**/*.tf"
      - ".github/workflows/release.yaml"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'sizzldev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 24.1.0
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
          branches: |
            ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
